source(paste(getwd(),"/source/CreateLandscape.R",sep=""))
source(paste(getwd(),"/source/CreatePopulation.R",sep=""))
source(paste(getwd(),"/source/PlotPopulation.R",sep=""))
source(paste(getwd(),"/source/MultiplePopulations.R",sep=""))
source(paste(getwd(),"/source/Movement.R",sep=""))
